json:
    path:     /json/{type}/{ID}
    defaults: { _controller: NewBundle:Default:json }
xml:
    path:     /xml/{type}/{ID}
    defaults: { _controller: NewBundle:Default:xml }    
clearDatabase:
    path: /database/truncate
    defaults: { _controller: NewBundle:Default:clearDatabase }
compareTest:
    path: /compare/{firstPersonOID}/{secondPersonOID}
    defaults: { _controller: NewBundle:Default:comparePerson }