json:
    path:     /json/{type}/{ID}
    defaults: { _controller: NewBundle:Default:json }
xml:
    path:     /xml/{type}/{ID}
    defaults: { _controller: NewBundle:Default:xml }    
newClearDatabase:
    path: /database/truncate
    defaults: { _controller: NewBundle:Default:clearDatabase }
compareTest:
    path: /compare/{firstPersonOID}/{secondPersonOID}
    defaults: { _controller: NewBundle:Default:comparePerson }
    
relatives:
    path: /relatives/{ID}
    defaults: { _controller: NewBundle:Relative:id }
    
direct_relatives:
    path: direct/relatives/{ID}
    defaults: { _controller: NewBundle:Relative:directId }