services:
#    new.example:
#        class: UR\DB\NewBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    migrate_data.service:
        class: UR\DB\NewBundle\Utils\MigrateData
        arguments: 
           container: "@service_container"
    person_merging.service:
        class: UR\DB\NewBundle\Utils\PersonMerger
        arguments: 
           container: "@service_container"
    response_builder.service:
        class: UR\DB\NewBundle\Utils\ResponseBuilder
        arguments: 
           container: "@service_container"
    normalization.service:
        class: UR\DB\NewBundle\Utils\NormalizationService
        arguments: 
           container: "@service_container"
    locationToTerritory.service:
        class: UR\DB\NewBundle\Utils\LocationToTerritoryMappingService
        arguments: 
           container: "@service_container"
    locationGeodata.service:
        class: UR\DB\NewBundle\Utils\LocationGeodataService
        arguments: 
           container: "@service_container"
    comparer.service:
        class: UR\DB\NewBundle\Utils\PersonComparer
        arguments: 
           container: "@service_container"
           
    util_object_handler.service:
        class: UR\DB\NewBundle\Utils\UtilObjHandler       
        arguments: 
           container: "@service_container"
           
    date_reference_loader:
        class: UR\DB\NewBundle\Utils\DateReferenceLoader       
        arguments: 
           container: "@service_container"
           
# listener/ subscriber
    fixDBOrder.subscriber:
            class: UR\DB\NewBundle\Utils\FixDBOrdersEventSubscriber
            arguments: 
                container: "@service_container"
            tags:
                - { name: doctrine.event_subscriber, connection: new }
                
    persistDates.subscriber:
            class: UR\DB\NewBundle\Utils\DateReferenceSubscriber
            arguments: 
                container: "@service_container"
            tags:
                - { name: doctrine.event_subscriber, connection: new }
                - { name: doctrine.event_subscriber, connection: final }      
                
    datereference_jms_handler:
        class: UR\DB\NewBundle\Utils\DateReferenceSerializationHandler
        arguments: 
                container: "@service_container"
        tags:
            - { name: jms_serializer.subscribing_handler }