services:
#    new.example:
#        class: UR\DB\NewBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    migrate_data.service:
        class: UR\DB\NewBundle\Utils\MigrateData
        arguments: 
           container: "@service_container"
    person_merging.service:
        class: UR\DB\NewBundle\Utils\PersonMerger
        arguments: 
           container: "@service_container"
    response_builder.service:
        class: UR\DB\NewBundle\Utils\ResponseBuilder
        arguments: 
           container: "@service_container"