amburger_homepage:
    path:     /hello/{name}
    defaults: { _controller: AmburgerBundle:Default:index }

amburger_homepage2:
    path:     /test/
    defaults: { _controller: AmburgerBundle:Default:test }

test_old:
    path:     /test/old/{ID}
    defaults: { _controller: AmburgerBundle:OldDB:person }

migrate:
    path:     /migrate/{ID}
    defaults: { _controller: AmburgerBundle:Migrate:person }
    
overview:
    path:     /overview/
    defaults: { _controller: AmburgerBundle:Default:overview }