<?php

namespace UR\AmburgerBundle\Entity;

/**
 * PersonDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonDataRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get random entities
     *
     * @param int $count Entities count, default is 10
     *
     * @return array
     */
    public function getRandomEntities($count = 1)
    {
        return $this->createQueryBuilder('p')
                ->addSelect('RAND() as HIDDEN rand')
                ->where('p.currentlyInProcess = false AND p.completed = false')
                ->addOrderBy('rand')
                ->setMaxResults($count)
                ->getQuery()
                ->getResult();
    }
}
