<?php

namespace UR\AmburgerBundle\Entity;

/**
 * PersonDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonDataRepository extends \Doctrine\ORM\EntityRepository
{
}
