final_homepage:
    path:     /hello/{name}
    defaults: { _controller: FinalBundle:Default:index }
    
finalClearDatabase:
    path: /database/truncate
    defaults: { _controller: FinalBundle:Default:clearDatabase }