
#@TODO: Think about moving start to correction?
start:
    path:     /start/
    defaults: { _controller: AmburgerBundle:CorrectionStart:index }
    methods: [GET]
    
checkOID:
    path:     /start/{OID}/check
    defaults: { _controller: AmburgerBundle:CorrectionStart:check }
    methods: [GET]

nextOID:
    path:     /start/next
    defaults: { _controller: AmburgerBundle:CorrectionStart:next }
    methods: [GET]

startWork:
    path:     /start/{OID}
    defaults: { _controller: AmburgerBundle:CorrectionStart:startWork }
    methods: [POST]

# duplicate
duplicate:
    path:    /correction/{OID}/duplicate/
    defaults: { _controller: AmburgerBundle:CorrectionDuplicate:index } 
    methods: [GET]
    
duplicate_load:
    path:    /correction/{OID}/duplicate/load
    defaults: { _controller: AmburgerBundle:CorrectionDuplicate:load } 
    methods: [GET]
    
# person correction

person:
    path:    /correction/{OID}/person/
    defaults: { _controller: AmburgerBundle:CorrectionPerson:index } 
    methods: [GET]
    
person_load:
    path:    /correction/{OID}/person/load
    defaults: { _controller: AmburgerBundle:CorrectionPerson:load } 
    methods: [GET]
    
person_load_wedding:
    path:    /correction/{ID}/person/load/wedding
    defaults: { _controller: AmburgerBundle:CorrectionPerson:loadWedding } 
    methods: [GET]    

    
person_save:
    path:    /correction/{OID}/person/save
    defaults: { _controller: AmburgerBundle:CorrectionPerson:save } 
    methods: [POST]

#person_relatives
person_relatives:
    path:    /correction/{OID}/relatives/
    defaults: { _controller: AmburgerBundle:CorrectionRelatives:index } 
    methods: [GET]
    
person_relatives_load:
    path:    /correction/{OID}/relatives/load
    defaults: { _controller: AmburgerBundle:CorrectionRelatives:loadPerson } 
    methods: [GET]
    
person_relatives_possible:
    path:    /correction/{OID}/relatives/possible
    defaults: { _controller: AmburgerBundle:CorrectionRelatives:findPossibleRelatives } 
    methods: [GET]
    
person_relatives_direct:
    path:    /correction/{OID}/relatives/direct
    defaults: { _controller: AmburgerBundle:CorrectionRelatives:loadDirectRelatives } 
    methods: [GET]
    
person_relatives_create:
    path:    /correction/{OID}/relatives/create
    defaults: { _controller: AmburgerBundle:CorrectionRelatives:create } 
    methods: [PUT]
        
person_relatives_update:
    path:    /correction/{OID}/relatives/update
    defaults: { _controller: AmburgerBundle:CorrectionRelatives:update } 
    methods: [POST]
    
person_relatives_remove:
    path:    /correction/{OID}/relatives/remove
    defaults: { _controller: AmburgerBundle:CorrectionRelatives:remove } 
    methods: [POST]