# usercontrol

user_settings:
    path: /settings/
    defaults: { _controller: AmburgerBundle:User:index }    
    methods: [GET]
    
user_settings_save:
    path: /settings/
    defaults: { _controller: AmburgerBundle:User:save }    
    methods: [POST]

addUser_index:
    path: /user/
    defaults: { _controller: AmburgerBundle:User:index }    
    methods: [GET]

addUser:
    path: /user/
    defaults: { _controller: AmburgerBundle:User:addUser }    
    methods: [POST]