UR\DB\FinalBundle\Entity\IsGrandparent:
    type: entity
    table: is_grandparent
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        grandParentid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: grand_parentID
        grandChildid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: grand_childID
        relationType:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: relation_type
        isPaternal:
            type: boolean
            nullable: false
            options:
                comment: 'mütterlicherseits und väterlicherseits!'
            column: is_paternal
        comment:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
    lifecycleCallbacks: {  }
