UR\AmburgerBundle\Entity\CorrectionSession:
    type: entity
    table: correction_session
    id:
        oid:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: OID
            id: true
    fields:
        activeUserName:
            type: string
            nullable: false
            comment: 'Currently active user name in session'
        activeUserId:
            type: string
            nullable: false
            comment: 'Currently active user id in session'
        sessionIdentifier:
            type: string
            nullable: false
            comment: 'Identifier for active session'
        created:
            type: datetime
            nullable: false
        modified:
            type: datetime
            nullable: false
    lifecycleCallbacks:
        preFlush: [updateCreatedAndModified]