UR\AmburgerBundle\Entity\OriginOfData:
    type: entity
    table: origin_of_data
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        person_id:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: person_id
            comment: 'The id of the person to which this data belongs.'
        data:
            type: blob
            nullable: false
            comment: 'The serialized data.'
        created:
            type: datetime
            nullable: false
        modified:
            type: datetime
            nullable: false
    lifecycleCallbacks:
        preFlush: [updateCreatedAndModified]