UR\AmburgerBundle\Entity\PersonData:
    type: entity
    repositoryClass: UR\AmburgerBundle\Entity\PersonDataRepository
    table: person_data
    id:
        oid:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: OID
            id: true
    fields:
        currentlyInProcess:
            type: boolean
            nullable: false
            options:
                default: false
            comment: 'Flag if currently someone is working on this person'
        completed:
            type: boolean
            nullable: false
            options:
                default: false
            comment: 'Flag if the person was corrected completly'
        created:
            type: datetime
            nullable: false
        modified:
            type: datetime
            nullable: false
    lifecycleCallbacks:
        preFlush: [updateCreatedAndModified]