UR\AmburgerBundle\Entity\PersonData:
    type: entity
    repositoryClass: UR\AmburgerBundle\Entity\PersonDataRepository
    table: person_data
    indexes:
        completed_idx:
            columns: [ completed ]
    id:
        personId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: person_id
            id: true
    fields:
        currentlyInProcess:
            type: boolean
            nullable: false
            options:
                default: false
            comment: 'Flag if currently someone is working on this person'
        completed:
            type: boolean
            nullable: false
            options:
                default: false
            comment: 'Flag if the person was corrected completly'
        created:
            type: datetime
            nullable: false
            columnDefinition: datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
        modified:
            type: datetime
            nullable: false
            columnDefinition: datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
    lifecycleCallbacks:
        preFlush: [updateCreatedAndModified]