UR\AmburgerBundle\Entity\User:
    type: entity
    repositoryClass: UR\AmburgerBundle\Entity\UserRepository
    table: user
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        password:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }