UR\AmburgerBundle\Entity\User:
    type: entity
    repositoryClass: UR\AmburgerBundle\Entity\UserRepository
    table: user
    indexes:
        user_password_idx:
            columns: [ name,password ]
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        password:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        admin:
            type: boolean
            options:
                default: false
    lifecycleCallbacks: {  }