<?php

namespace UR\DB\NewBundle\Entity;

use Doctrine\ORM\EntityRepository;
use UR\DB\NewBundle\Entity\Date;
/**
 * DeathRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeathRepository extends EntityRepository
{
	public function setDeathDates($deathObj, $dateIdArray){

		$uniqueArray = array_unique($dateIdArray);

		$newDateString = implode(",", $uniqueArray);

        $deathObj->setDeathDateId($newDateString);

        //$this->persist($deathObj);
        //$this->flush();
	}
   
    public function addDeathDate($deathObj, $dateId){
        $currentDateString = $deathObj->getDeathDateId();

        //expected input: id1,id5,id6
        $dateIdArray = explode(",", $currentDateString);

        foreach($dateIdArray as $currdateId){
        	if($dateId == trim($currdateId)){
        		//date in string ==> no work to do
        		return;
        	}
        }

        //date not in string
        $currentDateString .= ",".$dateId;

        $deathObj->setDeathDateId($currentDateString);

        //$this->persist($deathObj);
        //$this->flush();
    }

    public function removeDeathDate($deathObj, $dateId){
        $currentDateString = $deathObj->getDeathDateId();

        //expected input: id1,id5,id6
        $dateIdArray = explode(",", $currentDateString);

        $indexFound = -1;

        for($i = 0; $i < count($dateIdArray); $i++){
        	if($dateId == trim($dateIdArray[$i])){
        		//date in string... need to remove it!
        		$indexFound = $i;
        	}
        }

        unset($dateIdArray[$i]);
        $newIdArray = array_values($dateIdArray);

        $newDateString = implode(",", $newIdArray);

        $deathObj->setDeathDateId($newDateString);

        //$this->persist($deathObj);
        //$this->flush();
    }


    public function setFuneralDates($deathObj, $dateIdArray){

		$uniqueArray = array_unique($dateIdArray);

		$newDateString = implode(",", $uniqueArray);

        $deathObj->setFuneralDateId($newDateString);

        //$this->persist($deathObj);
        //$this->flush();
	}
   
    public function addFuneralDate($deathObj, $dateId){
        $currentDateString = $deathObj->getFuneralDateId();

        //expected input: id1,id5,id6
        $dateIdArray = explode(",", $currentDateString);

        foreach($dateIdArray as $currdateId){
        	if($dateId == trim($currdateId)){
        		//date in string ==> no work to do
        		return;
        	}
        }

        //date not in string
        $currentDateString .= ",".$dateId;

        $deathObj->setFuneralDateId($currentDateString);

        //$this->persist($deathObj);
        //$this->flush();
    }

    public function removeFuneralDate($deathObj, $dateId){
        $currentDateString = $deathObj->getFuneralDateId();

        //expected input: id1,id5,id6
        $dateIdArray = explode(",", $currentDateString);

        $indexFound = -1;

        for($i = 0; $i < count($dateIdArray); $i++){
        	if($dateId == trim($dateIdArray[$i])){
        		//date in string... need to remove it!
        		$indexFound = $i;
        	}
        }

        unset($dateIdArray[$i]);
        $newIdArray = array_values($dateIdArray);

        $newDateString = implode(",", $newIdArray);

        $deathObj->setFuneralDateId($newDateString);

        //$this->persist($deathObj);
        //$this->flush();
    }

}