<?php

namespace UR\DB\NewBundle\Entity;

use Doctrine\ORM\EntityRepository;
/**
 * IsParentInLawRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IsParentInLawRepository extends EntityRepository
{
   
    public function loadParentsInLaw($ID)
    {
        
        $queryBuilder = $this->_em->getRepository('NewBundle:IsParentInLaw')->createQueryBuilder('p');

        return $queryBuilder
                ->where('p.childInLawid = :id')
                ->setParameter('id', $ID)
                ->getQuery()
                ->getResult();
    }
    
    public function loadChildrenInLaw($ID)
    {
        
        $queryBuilder = $this->_em->getRepository('NewBundle:IsParentInLaw')->createQueryBuilder('p');

        return $queryBuilder
                ->where('p.parentInLawid = :id')
                ->setParameter('id', $ID)
                ->getQuery()
                ->getResult();
    }
}