<?php

namespace UR\DB\NewBundle\Entity;

use Doctrine\ORM\EntityRepository;
/**
 * IsParentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IsParentRepository extends EntityRepository
{
   
    public function loadParents($ID)
    {
        
        $queryBuilder = $this->_em->getRepository('NewBundle:IsParent')->createQueryBuilder('p');

        return $queryBuilder
                ->where('p.childID = :id')
                ->setParameter('id', $ID)
                ->getQuery()
                ->getResult();
    }
    
    public function loadChildren($ID)
    {
        
        $queryBuilder = $this->_em->getRepository('NewBundle:IsParent')->createQueryBuilder('p');

        return $queryBuilder
                ->where('p.parentID = :id')
                ->setParameter('id', $ID)
                ->getQuery()
                ->getResult();
    }
}