<?php

namespace UR\DB\NewBundle\Entity;

use Doctrine\ORM\EntityRepository;
/**
 * IsSiblingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IsSiblingRepository extends EntityRepository
{
   
    public function loadSiblings($ID)
    {
        
        $queryBuilder = $this->_em->getRepository('NewBundle:IsSibling')->createQueryBuilder('s');

        return $queryBuilder
                ->where('s.siblingOneid = :id OR s.siblingTwoid = :id')
                ->setParameter('id', $ID)
                ->getQuery()
                ->getResult();
    }
}