<?php

namespace UR\DB\NewBundle\Entity;

use Doctrine\ORM\EntityRepository;
/**
 * IsSiblingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends EntityRepository
{
   
    public function getIDForOID($OID)
    {
        
        $queryBuilder = $this->_em->getRepository('NewBundle:Person')->createQueryBuilder('p');

        return $queryBuilder
                ->select('p.id')
                ->where('p.oid = :oid')
                ->setParameter('oid', $OID)
                ->getQuery()
                ->getOneOrNullResult();
    }
    
    public function getOIDForID($ID)
    {
        
        $queryBuilder = $this->_em->getRepository('NewBundle:Person')->createQueryBuilder('p');

        return $queryBuilder
                ->select('p.oid')
                ->where('p.id = :id')
                ->setParameter('id', $ID)
                ->getQuery()
                ->getOneOrNullResult();
    }
}