<?php

namespace UR\DB\NewBundle\Entity;

use Doctrine\ORM\EntityRepository;
/**
 * UniqueIDSequenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UniqueIDSequenceRepository extends EntityRepository
{
   
    public function nextId(){
         
        $sequences = $this->findAll();
        
        if(count($sequences) == 0){
            $sequence = $this->createNewSequence();
            return $sequence->getCurrentHighestId();
        } else {
            if(count($sequences) > 1){
                //should not happen!
            }
            
            //update sequence +1
            
            $newHighestId = $sequences[0]->getCurrentHighestId() +1;
            
            $sequences[0]->setCurrentHighestId($newHighestId);
            
            $this->getEntityManager()->persist($sequences[0]);
            
            //return value
            return $newHighestId;
        }
        
    }

    private function createNewSequence(){
        $newSequence = new UniqueIDSequence();
        $newSequence->setCurrentHighestId(1);
        
        $this->getEntityManager()->persist($newSequence);
        
        return $newSequence;
    }
}