<?php

namespace UR\DB\NewBundle\Entity;

use Doctrine\ORM\EntityRepository;
/**
 * WeddingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeddingRepository extends EntityRepository
{
   
    public function loadMarriagePartners($ID)
    {
        
        $queryBuilder = $this->_em->getRepository('NewBundle:Wedding')->createQueryBuilder('w');

        return $queryBuilder
                ->where('w.husbandId = :id OR w.wifeId = :id')
                ->setParameter('id', $ID)
                ->getQuery()
                ->getResult();
    }
    
   public function loadWeddingsForHusband($ID)
    {
        
        $queryBuilder = $this->_em->getRepository('NewBundle:Wedding')->createQueryBuilder('w');

        return $queryBuilder
                ->where('w.husbandId = :id')
                ->setParameter('id', $ID)
                ->getQuery()
                ->getResult();
    }
    
    public function loadWeddingsForWife($ID)
    {
        
        $queryBuilder = $this->_em->getRepository('NewBundle:Wedding')->createQueryBuilder('w');

        return $queryBuilder
                ->where('w.wifeId = :id')
                ->setParameter('id', $ID)
                ->getQuery()
                ->getResult();
    }
}