UR\DB\NewBundle\Entity\Baptism:
    type: entity
    table: baptism
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        baptismDateid:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: baptism_dateID
        baptismLocationid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: baptism_locationID
    manyToOne:
        person:
            targetEntity: BasePerson
        baptismLocation:
            targetEntity: Location
            fetch: EAGER
            joinColumn:
                name: baptism_locationID
                referencedColumnName: ID
                nullable: true
                
    lifecycleCallbacks: {  }
