UR\DB\NewBundle\Entity\Baptism:
    type: entity
    table: baptism
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        baptismDateid:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: baptism_dateID
        baptismLocationid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: baptism_locationID
        personID:
            type: integer
            nullable: false
            column: person_ID
            options:
                comment: 'can be a reference to person, partner or relative'
    lifecycleCallbacks: {  }
