UR\DB\NewBundle\Entity\Baptism:
    type: entity
    repositoryClass: UR\DB\NewBundle\Entity\BaptismRepository
    table: baptism
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        baptismDateid:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: baptism_dateID
        baptismLocationid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: baptism_locationID
    lifecycleCallbacks: {  }
