UR\DB\NewBundle\Entity\Birth:
    type: entity
    table: birth
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        originCountryid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: origin_countryID
        originTerritoryid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: origin_territoryID
        originLocationid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: origin_locationID
        birthCountryid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: birth_countryID
        birthLocationid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: birth_locationID
        birthDateid:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: birth_dateID
        birthTerritoryid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: birth_territoryID
        comment:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
    manyToOne:
        person:
            targetEntity: BasePerson
        originCountry:
            targetEntity: Country
            fetch: EAGER
            joinColumn:
                name: origin_countryID
                referencedColumnName: ID
                nullable: true
        originTerritory:
            targetEntity: Territory
            fetch: EAGER
            joinColumn:
                name: origin_territoryID
                referencedColumnName: ID
                nullable: true
        originLocation:
            targetEntity: Location
            fetch: EAGER
            joinColumn:
                name: origin_locationID
                referencedColumnName: ID
                nullable: true
        birthCountry:
            targetEntity: Country
            fetch: EAGER
            joinColumn:
                name: birth_countryID
                referencedColumnName: ID
                nullable: true        
        birthTerritory:
            targetEntity: Territory
            fetch: EAGER
            joinColumn:
                name: birth_territoryID
                referencedColumnName: ID
                nullable: true
        birthLocation:
            targetEntity: Location
            fetch: EAGER
            joinColumn:
                name: birth_locationID
                referencedColumnName: ID
                nullable: true        
    lifecycleCallbacks: {  }
