UR\DB\NewBundle\Entity\Date:
    type: entity
    table: date
    options:
        collate: utf8_general_ci
        charset: utf8
    indexes:
        day_idx:
            columns: [ day ]
        month_idx:
            columns: [ month ]
        year_idx:
            columns: [ year ]
        before_idx:
            columns: [ before_date ]
        after_idx:
            columns: [ after_date ]
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        day:
            type: integer
            nullable: true
            options:
                fixed: false
        month:
            type: integer
            nullable: true
            options:
                fixed: false
        year:
            type: integer
            nullable: true
            options:
                fixed: false
        weekday:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
        comment:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        beforeDate:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: before_date
        afterDate:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: after_date
    lifecycleCallbacks: {  }
