UR\DB\NewBundle\Entity\Death:
    type: entity
    table: death
    options:
        collate: utf8_general_ci
        charset: utf8
    indexes:
        death_date_idx:
            columns: [ death_dateID ]
        funeral_date_idx:
            columns: [ funeral_dateID ]
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        deathLocationid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: death_locationID
        deathCountryid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: death_countryID
        causeOfDeath:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: cause_of_death
        territoryOfDeathid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: territory_of_deathID
        graveyard:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        funeralLocationid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: funeral_locationID
        comment:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: death_comment
        deathDate:
            type: date_reference
            column: death_dateId
            nullable: true
        funeralDate:
            type: date_reference
            column: funeral_dateId
            nullable: true
    manyToOne:
        deathCountry:
            targetEntity: Country
            fetch: EAGER
            joinColumn:
                name: death_countryID
                referencedColumnName: ID
                nullable: true
            cascade: ["persist"]
        territoryOfDeath:
            targetEntity: Territory
            fetch: EAGER
            joinColumn:
                name: territory_of_deathID
                referencedColumnName: ID
                nullable: true
            cascade: ["persist"]
        deathLocation:
            targetEntity: Location
            fetch: EAGER
            joinColumn:
                name: death_locationID
                referencedColumnName: ID
                nullable: true        
            cascade: ["persist"]    
        funeralLocation:
            targetEntity: Location
            fetch: EAGER
            joinColumn:
                name: funeral_locationID
                referencedColumnName: ID
                nullable: true
            cascade: ["persist"]
    lifecycleCallbacks: {  }
