UR\DB\NewBundle\Entity\Education:
    type: entity
    table: education
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        educationOrder:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: education_order
        label:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        countryid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: countryID
        territoryid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: territoryID
        locationid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: locationID
        fromDateid:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: from_dateID
        toDateid:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: to_dateID
        provenDateid:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: proven_dateID
        graduationLabel:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: graduation_label
        graduationDateid:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: graduation_dateID
        graduationLocationid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: graduation_locationID
        comment:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        personID:
            type: integer
            nullable: false
            column: person_ID
            options:
                comment: 'can be a reference to person, partner or relative'
    lifecycleCallbacks: {  }
