UR\DB\NewBundle\Entity\Education:
    type: entity
    table: education
    options:
        collate: utf8_general_ci
        charset: utf8
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        educationOrder:
            type: integer
            nullable: false
            options:
                default: '1'
            column: education_order
        label:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        countryid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: countryID
        territoryid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: territoryID
        locationid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: locationID
        fromDate:
            type: date_reference
            column: from_dateID
            nullable: true
        toDate:
            type: date_reference
            column: to_dateID
            nullable: true
        provenDate:
            type: date_reference
            column: proven_dateID
            nullable: true
        graduationLabel:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: graduation_label
        graduationDate:
            type: date_reference
            column: graduation_dateID
            nullable: true
        graduationLocationid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: graduation_locationID
        comment:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
    manyToOne:
        person:
            targetEntity: BasePerson
            cascade: ["persist"]
        country:
            targetEntity: Country
            fetch: EAGER
            joinColumn:
                name: countryID
                referencedColumnName: ID
                nullable: true
            cascade: ["persist"]
        territory:
            targetEntity: Territory
            fetch: EAGER
            joinColumn:
                name: territoryID
                referencedColumnName: ID
                nullable: true
            cascade: ["persist"]        
        location:
            targetEntity: Location
            fetch: EAGER
            joinColumn:
                name: locationID
                referencedColumnName: ID
                nullable: true   
            cascade: ["persist"]
        graduationLocation:
            targetEntity: Location
            fetch: EAGER
            joinColumn:
                name: graduation_locationID
                referencedColumnName: ID
                nullable: true     
            cascade: ["persist"]
    lifecycleCallbacks: {  }
