UR\DB\NewBundle\Entity\IsGrandchild:
    type: entity
    table: is_grandchild
    uniqueConstraints:
        grand_parentID:
            columns:
                - grand_parentID
                - grand_childID
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID
        grandParentid:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            id: true
            column: grand_parentID
        grandChildid:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            id: true
            column: grand_childID
    fields:
        relationType:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: relation_type
        comment:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
    lifecycleCallbacks: {  }
