UR\DB\NewBundle\Entity\IsGrandparent:
    type: entity
    table: is_grandparent
    options:
        collate: utf8_general_ci
        charset: utf8
    uniqueConstraints:
        grand_parentID:
            columns:
                - grandparentID
                - grandchildID
                - relation_type
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        grandParentID:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: grandparentID
        grandChildID:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: grandchildID
        relationType:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: relation_type
        isPaternal:
            type: boolean
            nullable: false
            options:
                comment: 'mütterlicherseits und väterlicherseits!'
            column: is_paternal
        comment:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
    lifecycleCallbacks: {  }
