UR\DB\NewBundle\Entity\IsInRelationshipWith:
    type: entity
    table: is_in_relationship_with
    options:
        collate: utf8_general_ci
        charset: utf8
    uniqueConstraints:
        first_partnerID:
            columns:
                - first_partnerID
                - second_partnerID
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        firstPartnerID:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: first_partnerID
        secondPartnerID:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: second_partnerID
        comment:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
    lifecycleCallbacks: {  }
