UR\DB\NewBundle\Entity\IsParent:
    type: entity
    table: is_parent
    uniqueConstraints:
        childID:
            columns:
                - childID
                - parentID
                - relation_type
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        childID:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: childID
        parentid:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: parentID
        relationType:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: relation_type
        comment:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
    lifecycleCallbacks: {  }
