# partner
UR\DB\NewBundle\Entity\Partner:
    type: entity
    table: partner
    inheritance:
        type: concrete
        extends: Entities\BasePerson 
    fields:
        originalNationid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: original_nationID