UR\DB\NewBundle\Entity\Person:
    type: entity
    table: person
    inheritance:
        type: concrete
        extends: Entities\BasePerson 
    uniqueConstraints:
        ID_OLD:
            columns:
                - OID
    fields:
        oid:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: OID
        originalNationid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: original_nationID
        control:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        complete:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
                
    oneToMany:
        sources:
          orderBy: { 'sourceOrder': 'ASC' }
          targetEntity: Source
          mappedBy: person
          fetch: EAGER
        births:
          targetEntity: Birth
          mappedBy: person
          fetch: EAGER
        baptisms:
          targetEntity: Baptism
          mappedBy: person
          fetch: EAGER
        deaths:
          targetEntity: Death
          mappedBy: person
          fetch: EAGER
        educations:
          orderBy: { 'educationOrder': 'ASC' }
          targetEntity: Education
          mappedBy: person
          fetch: EAGER
        honours:
          orderBy: { 'honourOrder': 'ASC' }
          targetEntity: Honour
          mappedBy: person
          fetch: EAGER
        properties:
          orderBy: { 'propertyOrder': 'ASC' }
          targetEntity: Property
          mappedBy: person
          fetch: EAGER
        ranks:
          orderBy: { 'rankOrder': 'ASC' }
          targetEntity: Rank
          mappedBy: person
          fetch: EAGER
        religions:
          orderBy: { 'religionOrder': 'ASC' }
          targetEntity: Religion
          mappedBy: person
          fetch: EAGER
        residences:
          orderBy: { 'residenceOrder': 'ASC' }
          targetEntity: Residence
          mappedBy: person
          fetch: EAGER
        roadOfLife:
          orderBy: { 'roadOfLifeOrder': 'ASC' }
          targetEntity: RoadOfLife
          mappedBy: person
          fetch: EAGER
        stati:
          orderBy: { 'statusOrder': 'ASC' }
          targetEntity: Status
          mappedBy: person
          fetch: EAGER
        works:
          orderBy: { 'worksOrder': 'ASC' }
          targetEntity: Works
          mappedBy: person
          fetch: EAGER