UR\DB\NewBundle\Entity\Rank:
    type: entity
    table: rank
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        rankOrder:
            type: integer
            nullable: false
            options:
                default: '1'
            column: rank_order
        label:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        class:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        countryid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: countryID
        territoryid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: territoryID
        locationid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: locationID
        fromDateid:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: from_dateID
        toDateid:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: to_dateID
        provenDateid:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: proven_dateID
        comment:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
    manyToOne:
        person:
            targetEntity: BasePerson
        country:
            targetEntity: Country
            fetch: EAGER
            joinColumn:
                name: countryID
                referencedColumnName: ID
                nullable: true        
        territory:
            targetEntity: Territory
            fetch: EAGER
            joinColumn:
                name: territoryID
                referencedColumnName: ID
                nullable: true
        location:
            targetEntity: Location
            fetch: EAGER
            joinColumn:
                name: locationID
                referencedColumnName: ID
                nullable: true              
    lifecycleCallbacks: {  }
