# relative
UR\DB\NewBundle\Entity\Relative:
    type: entity
    table: relative
    inheritance:
        type: concrete
        extends: Entities\BasePerson 
    fields:
        nationid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: nationID
    oneToOne:
        birth:
          targetEntity: Birth
          joinColumn:
            name: birth_id
            referencedColumnName: ID
            nullable: true
          fetch: EAGER
          cascade: ["remove"]
        baptism:
          targetEntity: Baptism
          joinColumn:
            name: baptism_id
            referencedColumnName: ID
            nullable: true
          fetch: EAGER
          cascade: ["remove"]
        death:
          targetEntity: Death
          joinColumn:
            name: death_id
            referencedColumnName: ID
            nullable: true
          fetch: EAGER
          cascade: ["remove"]
    oneToMany:
        educations:
          orderBy: { 'educationOrder': 'ASC' }
          targetEntity: Education
          mappedBy: person
          fetch: EAGER
          cascade: ["remove"]
        honours:
          orderBy: { 'honourOrder': 'ASC' }
          targetEntity: Honour
          mappedBy: person
          fetch: EAGER
          cascade: ["remove"]
        properties:
          orderBy: { 'propertyOrder': 'ASC' }
          targetEntity: Property
          mappedBy: person
          fetch: EAGER
          cascade: ["remove"]
        ranks:
          orderBy: { 'rankOrder': 'ASC' }
          targetEntity: Rank
          mappedBy: person
          fetch: EAGER
          cascade: ["remove"]
        religions:
          orderBy: { 'religionOrder': 'ASC' }
          targetEntity: Religion
          mappedBy: person
          fetch: EAGER
          cascade: ["remove"]
        residences:
          orderBy: { 'residenceOrder': 'ASC' }
          targetEntity: Residence
          mappedBy: person
          fetch: EAGER
          cascade: ["remove"]
        roadOfLife:
          orderBy: { 'roadOfLifeOrder': 'ASC' }
          targetEntity: RoadOfLife
          mappedBy: person
          fetch: EAGER
          cascade: ["remove"]
        stati:
          orderBy: { 'statusOrder': 'ASC' }
          targetEntity: Status
          mappedBy: person
          fetch: EAGER
          cascade: ["remove"]
        works:
          orderBy: { 'worksOrder': 'ASC' }
          targetEntity: Works
          mappedBy: person
          fetch: EAGER
          cascade: ["remove"]
    manyToOne:
        nation:
            targetEntity: Nation
            fetch: EAGER
            joinColumn:
                name: nationID
                referencedColumnName: ID
                nullable: true            