# relative
UR\DB\NewBundle\Entity\Relative:
    type: entity
    table: relative
    inheritance:
        type: concrete
        extends: Entities\BasePerson 
    fields:
        nationid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: nationID