# relative
UR\DB\NewBundle\Entity\Relative:
    type: entity
    table: relative
    options:
        collate: utf8_general_ci
        charset: utf8
    inheritance:
        type: concrete
        extends: Entities\BasePerson 
    indexes:
        # the name of the index
        relative_gender_idx:
            # Columns is an array, specify multiple columns for 
            # a compound index
            columns: [ gender ]
        relative_firstName_idx:
            columns: [ first_name ]
        relative_patronym_idx:
            columns: [ patronym ]
        relative_lastName_idx:
            columns: [ last_name ]
        relative_foreName_idx:
            columns: [ fore_name ]
        relative_birthName_idx:
            columns: [ birth_name ]
    fields:
    oneToMany:
        educations:
          orderBy: { 'educationOrder': 'ASC' }
          targetEntity: Education
          mappedBy: person
          fetch: EAGER
          cascade: ["persist","merge","remove"]
        honours:
          orderBy: { 'honourOrder': 'ASC' }
          targetEntity: Honour
          mappedBy: person
          fetch: EAGER
          cascade: ["persist","merge","remove"]
        properties:
          orderBy: { 'propertyOrder': 'ASC' }
          targetEntity: Property
          mappedBy: person
          fetch: EAGER
          cascade: ["persist","merge","remove"]
        ranks:
          orderBy: { 'rankOrder': 'ASC' }
          targetEntity: Rank
          mappedBy: person
          fetch: EAGER
          cascade: ["persist","merge","remove"]
        religions:
          orderBy: { 'religionOrder': 'ASC' }
          targetEntity: Religion
          mappedBy: person
          fetch: EAGER
          cascade: ["persist","merge","remove"]
        residences:
          orderBy: { 'residenceOrder': 'ASC' }
          targetEntity: Residence
          mappedBy: person
          fetch: EAGER
          cascade: ["persist","merge","remove"]
        roadOfLife:
          orderBy: { 'roadOfLifeOrder': 'ASC' }
          targetEntity: RoadOfLife
          mappedBy: person
          fetch: EAGER
          cascade: ["persist","merge","remove"]
        stati:
          orderBy: { 'statusOrder': 'ASC' }
          targetEntity: Status
          mappedBy: person
          fetch: EAGER
          cascade: ["persist","merge","remove"]
        works:
          orderBy: { 'worksOrder': 'ASC' }
          targetEntity: Works
          mappedBy: person
          fetch: EAGER
          cascade: ["persist","merge","remove"]