UR\DB\NewBundle\Entity\Religion:
    type: entity
    table: religion
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        comment:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        religionOrder:
            type: integer
            nullable: false
            options:
                default: '1'
            column: religion_order
        fromDate:
            type: date_reference
            column: from_dateID
            nullable: true
        provenDate:
            type: date_reference
            column: proven_dateID
            nullable: true
        changeOfReligion:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: change_of_religion
    manyToOne:
        person:
            targetEntity: BasePerson
    lifecycleCallbacks: {  }
