UR\DB\NewBundle\Entity\RoadOfLife:
    type: entity
    table: road_of_life
    options:
        collate: utf8_general_ci
        charset: utf8
    indexes:
        rol_from_date_idx:
            columns: [ from_dateID ]
        rol_to_date_idx:
            columns: [ to_dateID ]
        rol_proven_date_idx:
            columns: [ proven_dateID ]
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        roadOfLifeOrder:
            type: integer
            nullable: false
            options:
                default: '1'
            column: road_of_life_order
        originCountryid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: origin_countryID
        originTerritoryid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: origin_territoryID
        jobid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: jobID
        countryid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: countryID
        territoryid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: territoryID
        locationid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: locationID
        fromDate:
            type: date_reference
            column: from_dateID
            nullable: true
        toDate:
            type: date_reference
            column: to_dateID
            nullable: true
        provenDate:
            type: date_reference
            column: proven_dateID
            nullable: true
        comment:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: road_of_life_comment
    manyToOne:
        person:
            targetEntity: BasePerson
            cascade: ["persist", "merge"]
        originCountry:
            targetEntity: Country
            fetch: EAGER
            joinColumn:
                name: origin_countryID
                referencedColumnName: ID
                nullable: true        
            cascade: ["persist"]
        originTerritory:
            targetEntity: Territory
            fetch: EAGER
            joinColumn:
                name: origin_territoryID
                referencedColumnName: ID
                nullable: true
            cascade: ["persist"]
        job:
            targetEntity: Job
            fetch: EAGER
            joinColumn:
                name: jobID
                referencedColumnName: ID
                nullable: true        
            cascade: ["persist"]
        country:
            targetEntity: Country
            fetch: EAGER
            joinColumn:
                name: countryID
                referencedColumnName: ID
                nullable: true     
            cascade: ["persist"]
        territory:
            targetEntity: Territory
            fetch: EAGER
            joinColumn:
                name: territoryID
                referencedColumnName: ID
                nullable: true
            cascade: ["persist"]
        location:
            targetEntity: Location
            fetch: EAGER
            joinColumn:
                name: locationID
                referencedColumnName: ID
                nullable: true     
            cascade: ["persist"]
    lifecycleCallbacks: {  }
