UR\DB\NewBundle\Entity\Works:
    type: entity
    table: works
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        label:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        countryid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: countryID
        locationid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: locationID
        fromDate:
            type: date_reference
            column: from_dateID
            nullable: true
        toDate:
            type: date_reference
            column: to_dateID
            nullable: true
        provenDate:
            type: date_reference
            column: proven_dateID
        territoryid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: territoryID
        comment:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        worksOrder:
            type: integer
            nullable: false
            options:
                default: '1'
            column: works_order
    manyToOne:
        person:
            targetEntity: BasePerson 
        country:
            targetEntity: Country
            fetch: EAGER
            joinColumn:
                name: countryID
                referencedColumnName: ID
                nullable: true        
        territory:
            targetEntity: Territory
            fetch: EAGER
            joinColumn:
                name: territoryID
                referencedColumnName: ID
                nullable: true
        location:
            targetEntity: Location
            fetch: EAGER
            joinColumn:
                name: locationID
                referencedColumnName: ID
                nullable: true            
    lifecycleCallbacks: {  }
