UR\DB\OldBundle\Entity\AusbildungDesGeschwisters:
    type: entity
    table: ausbildung_des_geschwisters
    indexes:
        land:
            columns:
                - land
        von-ab:
            columns:
                - von-ab
        bis:
            columns:
                - bis
        ausbildung:
            columns:
                - ausbildung
        ort:
            columns:
                - ort
        bildungsabschluss:
            columns:
                - bildungsabschluss
        belegt:
            columns:
                - belegt
    id:
        order:
            type: boolean
            nullable: false
            id: true
        order2:
            type: boolean
            nullable: false
            id: true
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: ID
    fields:
        land:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        vonAb:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
            column: von-ab
        bis:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        ausbildung:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        ort:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        bildungsabschluss:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        belegt:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
    lifecycleCallbacks: {  }
