UR\DB\OldBundle\Entity\EhrenDesKindes:
    type: entity
    table: ehren_des_kindes
    indexes:
        land:
            columns:
                - land
        ehren:
            columns:
                - ehren
        ort:
            columns:
                - ort
        von-ab:
            columns:
                - von-ab
    id:
        order:
            type: boolean
            nullable: false
            id: true
        order2:
            type: boolean
            nullable: false
            id: true
        order3:
            type: boolean
            nullable: false
            id: true
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: ID
    fields:
        land:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        ehren:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        ort:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        vonAb:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
            column: von-ab
    lifecycleCallbacks: {  }
