UR\DB\OldBundle\Entity\Ehren:
    type: entity
    table: ehren
    indexes:
        land:
            columns:
                - land
        belegt:
            columns:
                - belegt
        ehren:
            columns:
                - ehren
        ort:
            columns:
                - ort
        territorium:
            columns:
                - territorium
        von-ab:
            columns:
                - von-ab
        bis:
            columns:
                - bis
        kommentar:
            columns:
                - kommentar
    id:
        order:
            type: boolean
            nullable: false
            id: true
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: ID
    fields:
        land:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        belegt:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        ehren:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        ort:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        territorium:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        vonAb:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
            column: von-ab
        bis:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        kommentar:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
    lifecycleCallbacks: {  }
