UR\DB\OldBundle\Entity\GroßmutterMuetterlicherseits:
    type: entity
    table: großmutter_muetterlicherseits
    indexes:
        vornamen:
            columns:
                - vornamen
        name:
            columns:
                - name
        nation:
            columns:
                - nation
    id:
        order:
            type: boolean
            nullable: false
            id: true
        order2:
            type: boolean
            nullable: false
            id: true
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: ID
    fields:
        vornamen:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        name:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        nation:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
    lifecycleCallbacks: {  }
