UR\DB\OldBundle\Entity\GroßvaterVaeterlicherseits:
    type: entity
    table: großvater_vaeterlicherseits
    indexes:
        vornamen:
            columns:
                - vornamen
        beruf:
            columns:
                - beruf
        geburtsort:
            columns:
                - geburtsort
        geburtsland:
            columns:
                - geburtsland
        geboren:
            columns:
                - geboren
        rang:
            columns:
                - rang
        name:
            columns:
                - name
        wohnort:
            columns:
                - wohnort
        gestorben:
            columns:
                - gestorben
        kommentar:
            columns:
                - kommentar
        stand:
            columns:
                - stand
        nation:
            columns:
                - nation
        geburtsterritorium:
            columns:
                - geburtsterritorium
        wohnterritorium:
            columns:
                - wohnterritorium
        vät_großvater_id-nr:
            columns:
                - vät_großvater_id-nr
    id:
        order:
            type: boolean
            nullable: false
            id: true
        order2:
            type: boolean
            nullable: false
            id: true
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: ID
    fields:
        vornamen:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        vätGroßvaterIdNr:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
            column: vät_großvater_id-nr
        beruf:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        geburtsort:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        geburtsland:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        geboren:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        rang:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        name:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        wohnort:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        gestorben:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        kommentar:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        stand:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        nation:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        geburtsterritorium:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        wohnterritorium:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
    lifecycleCallbacks: {  }
