UR\DB\OldBundle\Entity\HerkunftDesGeschwisters:
    type: entity
    table: herkunft_des_geschwisters
    indexes:
        geboren:
            columns:
                - geboren
        getauft:
            columns:
                - getauft
        taufort:
            columns:
                - taufort
        geburtsort:
            columns:
                - geburtsort
        kommentar:
            columns:
                - kommentar
        geburtsland:
            columns:
                - geburtsland
    id:
        order:
            type: boolean
            nullable: false
            id: true
        order2:
            type: boolean
            nullable: false
            id: true
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: ID
    fields:
        geboren:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        getauft:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        taufort:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        geburtsort:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        kommentar:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        geburtsland:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
    lifecycleCallbacks: {  }
