UR\DB\OldBundle\Entity\Mutter:
    type: entity
    table: mutter
    indexes:
        vornamen:
            columns:
                - vornamen
        name:
            columns:
                - name
        gestorben:
            columns:
                - gestorben
        herkunftsort:
            columns:
                - herkunftsort
        herkunftsterritorium:
            columns:
                - herkunftsterritorium
        konfession:
            columns:
                - konfession
        stand:
            columns:
                - stand
        todesort:
            columns:
                - todesort
        geboren:
            columns:
                - geboren
        friedhof:
            columns:
                - friedhof
        herkunftsland:
            columns:
                - herkunftsland
        wohnort:
            columns:
                - wohnort
        kommentar:
            columns:
                - kommentar
        getauft:
            columns:
                - getauft
        besitz:
            columns:
                - besitz
        beruf:
            columns:
                - beruf
        geburtsort:
            columns:
                - geburtsort
        nation:
            columns:
                - nation
        ehelich:
            columns:
                - ehelich
        rufnamen:
            columns:
                - rufnamen
        rang:
            columns:
                - rang
        begraben:
            columns:
                - begraben
        todesterritorium:
            columns:
                - todesterritorium
        russ_vornamen:
            columns:
                - russ_vornamen
        mutter_id-nr:
            columns:
                - mutter_id-nr
    id:
        order:
            type: boolean
            nullable: false
            id: true
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: ID
    fields:
        vornamen:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        name:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        gestorben:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        herkunftsort:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        herkunftsterritorium:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        russVornamen:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
            column: russ_vornamen
        konfession:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        stand:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        mutterIdNr:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
            column: mutter_id-nr
        todesort:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        geboren:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        friedhof:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        herkunftsland:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        wohnort:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        kommentar:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        getauft:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        besitz:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        beruf:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        geburtsort:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        nation:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        ehelich:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        rufnamen:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        rang:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        begraben:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        todesterritorium:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
    lifecycleCallbacks: {  }
