UR\DB\OldBundle\Entity\PartnerinDesVaters:
    type: entity
    table: partnerin_des_vaters
    indexes:
        name:
            columns:
                - name
        verheiratet:
            columns:
                - verheiratet
        vornamen:
            columns:
                - vornamen
        hochzeitstag:
            columns:
                - hochzeitstag
        gestorben:
            columns:
                - gestorben
        hochzeitsort:
            columns:
                - hochzeitsort
        geboren:
            columns:
                - geboren
        stand:
            columns:
                - stand
        vorher-nachher:
            columns:
                - vorher-nachher
        kommentar:
            columns:
                - kommentar
        beruf:
            columns:
                - beruf
        taufort:
            columns:
                - taufort
        getauft:
            columns:
                - getauft
        geburtsort:
            columns:
                - geburtsort
        todesort:
            columns:
                - todesort
    id:
        order:
            type: boolean
            nullable: false
            id: true
        order2:
            type: boolean
            nullable: false
            id: true
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: ID
    fields:
        name:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        verheiratet:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        vornamen:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        hochzeitstag:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        gestorben:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        hochzeitsort:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        geboren:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        stand:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        vorherNachher:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
            column: vorher-nachher
        kommentar:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        beruf:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        taufort:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        getauft:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        geburtsort:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        todesort:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
    lifecycleCallbacks: {  }
