UR\DB\OldBundle\Entity\Schwiegervater:
    type: entity
    table: schwiegervater
    indexes:
        vornamen:
            columns:
                - vornamen
        beruf:
            columns:
                - beruf
        rang:
            columns:
                - rang
        bildungsabschluss:
            columns:
                - bildungsabschluss
        name:
            columns:
                - name
        ehelich:
            columns:
                - ehelich
        wohnort:
            columns:
                - wohnort
        wohnterritorium:
            columns:
                - wohnterritorium
        ehren:
            columns:
                - ehren
        gestorben:
            columns:
                - gestorben
        geboren:
            columns:
                - geboren
        herkunftsort:
            columns:
                - herkunftsort
        todesort:
            columns:
                - todesort
        wohnland:
            columns:
                - wohnland
        herkunftsterritorium:
            columns:
                - herkunftsterritorium
        stand:
            columns:
                - stand
        kommentar:
            columns:
                - kommentar
        nation:
            columns:
                - nation
        taufort:
            columns:
                - taufort
        konfession:
            columns:
                - konfession
        begraben:
            columns:
                - begraben
        besitz:
            columns:
                - besitz
        hochzeitsort:
            columns:
                - hochzeitsort
        begräbnisort:
            columns:
                - begräbnisort
        getauft:
            columns:
                - getauft
        russ_vornamen:
            columns:
                - russ_vornamen
        schwiegervater_id-nr:
            columns:
                - schwiegervater_id-nr
    id:
        order:
            type: boolean
            nullable: false
            id: true
        order2:
            type: boolean
            nullable: false
            id: true
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: ID
    fields:
        vornamen:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        beruf:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        rang:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        bildungsabschluss:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        name:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        ehelich:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        wohnort:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        wohnterritorium:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        ehren:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        gestorben:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        geboren:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        herkunftsort:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        todesort:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        wohnland:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        russVornamen:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
            column: russ_vornamen
        herkunftsterritorium:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        stand:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        kommentar:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        nation:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        taufort:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        konfession:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        begraben:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        schwiegervaterIdNr:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
            column: schwiegervater_id-nr
        besitz:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        hochzeitsort:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        begräbnisort:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        getauft:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
    lifecycleCallbacks: {  }
