UR\DB\OldBundle\Entity\Vater:
    type: entity
    table: vater
    indexes:
        vornamen:
            columns:
                - vornamen
        beruf:
            columns:
                - beruf
        stand:
            columns:
                - stand
        bildungsabschluss:
            columns:
                - bildungsabschluss
        wohnort:
            columns:
                - wohnort
        geboren:
            columns:
                - geboren
        gestorben:
            columns:
                - gestorben
        herkunftsort:
            columns:
                - herkunftsort
        herkunftsterritorium:
            columns:
                - herkunftsterritorium
        rufnamen:
            columns:
                - rufnamen
        name:
            columns:
                - name
        geburtsterritorium:
            columns:
                - geburtsterritorium
        rang:
            columns:
                - rang
        geburtsort:
            columns:
                - geburtsort
        besitz:
            columns:
                - besitz
        ehren:
            columns:
                - ehren
        kommentar:
            columns:
                - kommentar
        todesort:
            columns:
                - todesort
        nation:
            columns:
                - nation
        todesterritorium:
            columns:
                - todesterritorium
        geburtsland:
            columns:
                - geburtsland
        konfession:
            columns:
                - konfession
        wohnland:
            columns:
                - wohnland
        herkunftsland:
            columns:
                - herkunftsland
        begraben:
            columns:
                - begraben
        getauft:
            columns:
                - getauft
        taufort:
            columns:
                - taufort
        begräbnisort:
            columns:
                - begräbnisort
        ausbildung:
            columns:
                - ausbildung
        russ_vornamen:
            columns:
                - russ_vornamen
    id:
        order:
            type: boolean
            nullable: false
            id: true
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: ID
    fields:
        vornamen:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        beruf:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        stand:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        bildungsabschluss:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        wohnort:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        russVornamen:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
            column: russ_vornamen
        geboren:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        gestorben:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        vaterIdNr:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
            column: vater_id-nr
        herkunftsort:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        herkunftsterritorium:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        rufnamen:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        name:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        wohnterritorium:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        geburtsterritorium:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        rang:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        geburtsort:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        besitz:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        ehren:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        ehelich:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        kommentar:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        todesort:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        nation:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        todesterritorium:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        geburtsland:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        konfession:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        wohnland:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        herkunftsland:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        begraben:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        getauft:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        taufort:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        begräbnisort:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        hochzeitstag:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        ausbildung:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
    lifecycleCallbacks: {  }
